[package]
name = "telemetry_poc"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
dashmap = "6.1"
serde_json = "1.0"
#reqwest = { version = "0.12", features = ["json"] }
